In [2]:
import pandas as pd

ALC_26_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC_Export.csv")
Geo_26_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Geography.csv")
Pro_26_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/xwalk_plus.csv")

ALC_25_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2024-25/ALC_Export.csv")
Geo_25_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2024-25/Geography.csv")
Pro_25_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2024-25/xwalk_plus.csv")

ALC_24_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2023-24/ALC_Export.csv")
# Geo_24_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2023-24/Geography.csv")
Pro_24_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2023-24/xwalk_plus.csv")

/var/folders/_v/58p7csjn63j_snd2sxrghlr00000gn/T/ipykernel_22722/3603380584.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  ALC_26_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC_Export.csv")
/var/folders/_v/58p7csjn63j_snd2sxrghlr00000gn/T/ipykernel_22722/3603380584.py:7: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  ALC_25_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2024-25/ALC_Export.csv")

In [12]:
Geo_24_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2023-24/Geography.csv", encoding="latin1")

In [13]:
print("ALC_26", ALC_26_df.shape)
print("Geo_26", Geo_26_df.shape)
print("Pro_26", Pro_26_df.shape)

ALC_26 (449440, 9)
Geo_26 (3275, 5)
Pro_26 (997, 5)

In [14]:
print("ALC_25", ALC_25_df.shape)
print("Geo_25", Geo_25_df.shape)
print("Pro_25", Pro_25_df.shape)

ALC_25 (451984, 9)
Geo_25 (4991, 5)
Pro_25 (997, 5)

In [15]:
print("ALC_24", ALC_24_df.shape)
print("Geo_24", Geo_24_df.shape)
print("Pro_24", Pro_24_df.shape)

ALC_24 (451984, 9)
Geo_24 (4988, 5)
Pro_24 (1367, 5)

In [18]:
ALC_26_df.head(5)

    Area  SocCode  GeoLvl  Level1  Level2  Level3  Level4  Average Label
0  10180  11-1011       1   47.73   74.99  102.25  129.51   102.53   NaN
1  10180  11-1021       1   19.91   33.72   47.52   61.33    47.66   NaN
2  10180  11-2021       1   32.55   46.09   59.62   73.16    59.76   NaN
3  10180  11-2022       1   29.61   45.10   60.60   76.09    60.75   NaN
4  10180  11-2032       1   28.38   36.39   44.40   52.41    44.48   NaN

In [19]:
Geo_26_df.head(5)

,Area,AreaName,StateAb,State,CountyTownName
0,1000005,Sussex Delaware nonmetropolitan area,DE,Delaware,Sussex County
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County

In [20]:
Pro_26_df.head(5)

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers
3,11-1031,Legislators,11-1031,11-1031.00,Legislators
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers

In [21]:
ALC_25_df.head(5)

    Area  SocCode  GeoLvl  Level1  Level2  Level3  Level4  Average Label
0  10180  11-1011       1   55.83   85.46  115.10  144.73   115.39   NaN
1  10180  11-1021       1   19.29   33.25   47.20   61.16    47.35   NaN
2  10180  11-2021       1   30.74   43.26   55.79   68.31    55.91   NaN
3  10180  11-2022       1   25.79   38.75   51.70   64.66    51.83   NaN
4  10180  11-2032       1   26.99   34.83   42.68   50.52    42.76   NaN

In [22]:
Geo_25_df.head(5)

,Area,AreaName,StateAb,State,CountyTownName
0,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Marion County

In [23]:
Pro_25_df.head(5)

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers
3,11-1031,Legislators,11-1031,11-1031.00,Legislators
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers

In [24]:
ALC_24_df.head(5)

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label
0,100001,11-1011,2,38.97,65.40,91.84,118.27,92.10,NaN
1,100001,11-1021,1,21.96,35.79,49.62,63.45,49.76,NaN
2,100001,11-1031,1,16370.00,19673.00,22977.00,26280.00,23010.00,Annual Wage
3,100001,11-2011,2,37.89,47.67,57.46,67.24,57.56,NaN
4,100001,11-2021,2,35.02,49.00,62.98,76.96,63.12,NaN

In [25]:
Geo_24_df.head(5)

,Area,AreaName,StateCode,State,CountyTownName
0,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",VA,Virginia,Fredericksburg city
1,49020,"Winchester, VA-WV",VA,Virginia,Winchester city
2,5300006,Western Washington nonmetropolitan area,WA,Washington,San Juan County
3,5300007,Eastern Washington nonmetropolitan area,WA,Washington,Whitman County
4,26580,"Huntington-Ashland, WV-KY-OH",WV,West Virginia,Putnam County

In [26]:
Pro_24_df.head(5)

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
0,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
1,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers
3,11-1031,Legislators,11-1031,11-1031.00,Legislators
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers