Do Over, trying to check the data

In [4]:
import pandas as pd

ALC_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/ALC_Export_26.csv")
Geo_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/Geography.csv")
Pro_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/xwalk_plus.csv")

/var/folders/_v/58p7csjn63j_snd2sxrghlr00000gn/T/ipykernel_22863/1477849685.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  ALC_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/ALC_Export_26.csv")

In [6]:
ALC_df.head()

    Area  SocCode  GeoLvl  Level1  Level2  Level3  Level4  Average Label
0  10180  11-1011       1   47.73   74.99  102.25  129.51   102.53   NaN
1  10180  11-1021       1   19.91   33.72   47.52   61.33    47.66   NaN
2  10180  11-2021       1   32.55   46.09   59.62   73.16    59.76   NaN
3  10180  11-2022       1   29.61   45.10   60.60   76.09    60.75   NaN
4  10180  11-2032       1   28.38   36.39   44.40   52.41    44.48   NaN

In [7]:
Geo_df.head()

,Area,AreaName,StateAb,State,CountyTownName
0,1000005,Sussex Delaware nonmetropolitan area,DE,Delaware,Sussex County
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County

In [9]:
Pro_df.head()

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers
3,11-1031,Legislators,11-1031,11-1031.00,Legislators
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers

In [11]:
Geo_df[Geo_df['StateAb'] == 'NJ']

,Area,AreaName,StateAb,State,CountyTownName
65,10900,"Allentown-Bethlehem-Easton, PA-NJ",NJ,New Jersey,Warren County
146,12100,"Atlantic City-Hammonton, NJ",NJ,New Jersey,Atlantic County
147,12100,"Atlantic City-Hammonton, NJ",NJ,New Jersey,Cape May County
1818,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Bergen County
1819,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Essex County
1820,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Hudson County
1821,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Hunterdon County
1822,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Middlesex County
1823,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Monmouth County
1824,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Morris County
1825,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Ocean County
1826,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Passaic County
1827,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Somerset County
1828,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Sussex County
1829,35620,"New York-Newark-Jersey City, NY-NJ",NJ,New Jersey,Union County
1972,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NJ,New Jersey,Burlington County
1973,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NJ,New Jersey,Camden County
1974,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NJ,New Jersey,Gloucester County
1975,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NJ,New Jersey,Salem County
2483,45940,"Trenton-Princeton, NJ",NJ,New Jersey,Mercer County
2618,47220,"Vineland, NJ",NJ,New Jersey,Cumberland County

In [12]:
Pro_df[Pro_df['ONetTitle'] == 'Information Technology Project Managers']

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
133,15-1299,"Computer Occupations, All Other",15-1299,15-1299.09,Information Technology Project Managers

In [30]:
ALC_df[ALC_df['Area'] == 12100 & ALC_df['SocCode'].str.contains('15', na=False)]
# ALC_df[ALC_df['Area'] == 12100]

Empty DataFrame
Columns: [Area, SocCode, GeoLvl, Level1, Level2, Level3, Level4, Average, Label]
Index: []

In [55]:
len(Geo_df['Area'].unique())

530

In [29]:
ALC_df[ALC_df['SocCode'].str.contains('11-1021', na=False)]

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label
1,10180,11-1021,1,19.91,33.72,47.52,61.33,47.66,NaN
261,10380,11-1021,1,20.57,30.99,41.40,51.82,41.51,NaN
433,10420,11-1021,1,24.06,41.55,59.04,76.53,59.22,NaN
869,10500,11-1021,1,21.60,35.55,49.51,63.46,49.64,NaN
1093,10540,11-1021,1,25.36,38.26,51.17,64.07,51.30,NaN
...,...,...,...,...,...,...,...,...,...
168672,5600007,11-1021,1,23.56,38.48,53.41,68.33,53.56,NaN
168949,6600001,11-1021,1,20.10,29.26,38.43,47.59,38.52,NaN
169143,7200006,11-1021,1,19.65,28.68,37.72,46.75,37.81,NaN
169255,7800001,11-1021,1,23.16,33.77,44.37,54.98,44.48,NaN
242235,41740,11-1021,2,33.38,57.46,81.55,105.63,81.79,NaN

<H1 color='red'>IT PM SocCode: 15-1299 present in data but not on dashboard

In [37]:
condition1 = ALC_df[ALC_df['Area'] == 12100]
condition2 = condition1[condition1['SocCode'].str.contains('15-1299', na=False)]

In [38]:
condition2

       Area  SocCode  GeoLvl  Level1  Level2  Level3  Level4  Average Label
6759  12100  15-1299       1   25.69   35.55    45.4   55.26     45.5   NaN

In [39]:
ALC_df.head()

    Area  SocCode  GeoLvl  Level1  Level2  Level3  Level4  Average Label
0  10180  11-1011       1   47.73   74.99  102.25  129.51   102.53   NaN
1  10180  11-1021       1   19.91   33.72   47.52   61.33    47.66   NaN
2  10180  11-2021       1   32.55   46.09   59.62   73.16    59.76   NaN
3  10180  11-2022       1   29.61   45.10   60.60   76.09    60.75   NaN
4  10180  11-2032       1   28.38   36.39   44.40   52.41    44.48   NaN

In [45]:
ALC_df['ALC_combined'] = ALC_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)
Geo_df['Geo_combined'] = Geo_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)
Pro_df['Pro_combined'] = Pro_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)

In [46]:
ALC_df.head()

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,ALC_combined
0,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,NaN,2026*10180*11-1011*1*47.73*74.99*102.25*129.51...
1,10180,11-1021,1,19.91,33.72,47.52,61.33,47.66,NaN,2026*10180*11-1021*1*19.91*33.72*47.52*61.33*4...
2,10180,11-2021,1,32.55,46.09,59.62,73.16,59.76,NaN,2026*10180*11-2021*1*32.55*46.09*59.62*73.16*5...
3,10180,11-2022,1,29.61,45.10,60.60,76.09,60.75,NaN,2026*10180*11-2022*1*29.61*45.1*60.6*76.09*60....
4,10180,11-2032,1,28.38,36.39,44.40,52.41,44.48,NaN,2026*10180*11-2032*1*28.38*36.39*44.4*52.41*44...

In [47]:
Geo_df.head()

,Area,AreaName,StateAb,State,CountyTownName,Geo_combined
0,1000005,Sussex Delaware nonmetropolitan area,DE,Delaware,Sussex County,2026*1000005*Sussex Delaware nonmetropolitan a...
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,2026*100001*Northwest Alabama nonmetropolitan ...
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County,2026*100001*Northwest Alabama nonmetropolitan ...
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County,2026*100001*Northwest Alabama nonmetropolitan ...
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County,2026*100001*Northwest Alabama nonmetropolitan ...

In [48]:
Pro_df.head()

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle,Pro_combined
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers,2026*11-1011*Chief Executives*11-1011*11-1011....
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives,2026*11-1011*Chief Executives*11-1011*11-1011....
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers,2026*11-1021*General and Operations Managers*1...
3,11-1031,Legislators,11-1031,11-1031.00,Legislators,2026*11-1031*Legislators*11-1031*11-1031.00*Le...
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers,2026*11-2011*Advertising and Promotions Manage...

<h3>Time to Merge the DFs

In [52]:
A= ALC_df
B= Geo_df

key_a = A.columns[0]   # 'id'
key_b = B.columns[0]   # 'id'

# B_indexed = B.set_index(key_b)  # set B's key as index for lookup
B_indexed = B.drop_duplicates(subset=key_b, keep='first').set_index(key_b)

for col in B_indexed.columns:
    A[col] = A[key_a].map(B_indexed[col])

In [53]:
ALC_df

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,ALC_combined,AreaName,StateAb,State,CountyTownName,Geo_combined
0,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,NaN,2026*10180*11-1011*1*47.73*74.99*102.25*129.51...,"Abilene, TX",TX,Texas,Callahan County,"2026*10180*Abilene, TX*TX*Texas*Callahan County"
1,10180,11-1021,1,19.91,33.72,47.52,61.33,47.66,NaN,2026*10180*11-1021*1*19.91*33.72*47.52*61.33*4...,"Abilene, TX",TX,Texas,Callahan County,"2026*10180*Abilene, TX*TX*Texas*Callahan County"
2,10180,11-2021,1,32.55,46.09,59.62,73.16,59.76,NaN,2026*10180*11-2021*1*32.55*46.09*59.62*73.16*5...,"Abilene, TX",TX,Texas,Callahan County,"2026*10180*Abilene, TX*TX*Texas*Callahan County"
3,10180,11-2022,1,29.61,45.10,60.60,76.09,60.75,NaN,2026*10180*11-2022*1*29.61*45.1*60.6*76.09*60....,"Abilene, TX",TX,Texas,Callahan County,"2026*10180*Abilene, TX*TX*Texas*Callahan County"
4,10180,11-2032,1,28.38,36.39,44.40,52.41,44.48,NaN,2026*10180*11-2032*1*28.38*36.39*44.4*52.41*44...,"Abilene, TX",TX,Texas,Callahan County,"2026*10180*Abilene, TX*TX*Texas*Callahan County"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449435,43100,45-3031,3,20.84,20.84,20.84,20.84,20.84,NaN,2026*43100*45-3031*3*20.84*20.84*20.84*20.84*2...,"Sheboygan, WI",WI,Wisconsin,Sheboygan County,"2026*43100*Sheboygan, WI*WI*Wisconsin*Sheboyga..."
449436,48260,45-3031,3,20.36,20.36,20.36,20.36,20.36,NaN,2026*48260*45-3031*3*20.36*20.36*20.36*20.36*2...,"Weirton-Steubenville, WV-OH",OH,Ohio,Jefferson County,"2026*48260*Weirton-Steubenville, WV-OH*OH*Ohio..."
449437,3900002,45-3031,1,21.43,21.43,21.43,21.43,21.43,NaN,2026*3900002*45-3031*1*21.43*21.43*21.43*21.43...,North Northeastern Ohio nonmetropolitan area (...,OH,Ohio,Ashland County,2026*3900002*North Northeastern Ohio nonmetrop...
449438,6600001,45-3031,1,20.39,20.39,20.39,20.39,20.39,NaN,2026*6600001*45-3031*1*20.39*20.39*20.39*20.39...,Guam MSA,GU,GUAM,ADELUP,2026*6600001*Guam MSA*GU*GUAM*ADELUP
449439,7800001,45-3031,1,19.27,19.27,19.27,19.27,19.27,NaN,2026*7800001*45-3031*1*19.27*19.27*19.27*19.27...,U.S. Virgin Islands MSA,VI,VIRGIN ISLANDS,ST. CROIX,2026*7800001*U.S. Virgin Islands MSA*VI*VIRGIN...

In [54]:
condition1 = ALC_df[ALC_df['Area'] == 12100]
condition2 = condition1[condition1['SocCode'].str.contains('15-1299', na=False)]
condition2

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,ALC_combined,AreaName,StateAb,State,CountyTownName,Geo_combined
6759,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,"Atlantic City-Hammonton, NJ",NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ..."

<h5> Re-initialize </h5>

In [56]:
ALC_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/ALC_Export_26.csv")
Geo_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/Geography.csv")
Pro_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/xwalk_plus.csv")
ALC_df['ALC_combined'] = ALC_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)
Geo_df['Geo_combined'] = Geo_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)
Pro_df['Pro_combined'] = Pro_df.apply(lambda x: '2026*' + '*'.join(x.astype(str)), axis=1)

/var/folders/_v/58p7csjn63j_snd2sxrghlr00000gn/T/ipykernel_22863/3794778867.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  ALC_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/ALC_Export_26.csv")

In [63]:
result = ALC_df.merge(Geo_df, on='Area', how='inner')
result2 = result.merge(Pro_df, left_on='SocCode', right_on='OES_SOCCODE', how='inner')

In [65]:
condition1 = result2[result2['Area'] == 12100]
condition2 = condition1[condition1['SocCode'].str.contains('15-1299', na=False)]
condition2

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,ALC_combined,...,StateAb,State,CountyTownName,Geo_combined,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle,Pro_combined
246495,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.07,Blockchain Engineers,"2026*15-1299*Computer Occupations, All Other*1..."
246496,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.05,Information Security Engineers,"2026*15-1299*Computer Occupations, All Other*1..."
246497,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.04,Penetration Testers,"2026*15-1299*Computer Occupations, All Other*1..."
246498,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.01,Web Administrators,"2026*15-1299*Computer Occupations, All Other*1..."
246499,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.06,Digital Forensics Analysts,"2026*15-1299*Computer Occupations, All Other*1..."
246500,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.03,Document Management Specialists,"2026*15-1299*Computer Occupations, All Other*1..."
246501,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.09,Information Technology Project Managers,"2026*15-1299*Computer Occupations, All Other*1..."
246502,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.08,Computer Systems Engineers/Architects,"2026*15-1299*Computer Occupations, All Other*1..."
246503,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.02,Geographic Information Systems Technologists a...,"2026*15-1299*Computer Occupations, All Other*1..."
246504,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Atlantic County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.00,"Computer Occupations, All Other","2026*15-1299*Computer Occupations, All Other*1..."
246505,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.07,Blockchain Engineers,"2026*15-1299*Computer Occupations, All Other*1..."
246506,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.05,Information Security Engineers,"2026*15-1299*Computer Occupations, All Other*1..."
246507,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.04,Penetration Testers,"2026*15-1299*Computer Occupations, All Other*1..."
246508,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.01,Web Administrators,"2026*15-1299*Computer Occupations, All Other*1..."
246509,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.06,Digital Forensics Analysts,"2026*15-1299*Computer Occupations, All Other*1..."
246510,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.03,Document Management Specialists,"2026*15-1299*Computer Occupations, All Other*1..."
246511,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.09,Information Technology Project Managers,"2026*15-1299*Computer Occupations, All Other*1..."
246512,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.08,Computer Systems Engineers/Architects,"2026*15-1299*Computer Occupations, All Other*1..."
246513,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.02,Geographic Information Systems Technologists a...,"2026*15-1299*Computer Occupations, All Other*1..."
246514,12100,15-1299,1,25.69,35.55,45.4,55.26,45.5,NaN,2026*12100*15-1299*1*25.69*35.55*45.4*55.26*45...,...,NJ,New Jersey,Cape May County,"2026*12100*Atlantic City-Hammonton, NJ*NJ*New ...",15-1299,"Computer Occupations, All Other",15-1299,15-1299.00,"Computer Occupations, All Other","2026*15-1299*Computer Occupations, All Other*1..."

In [66]:
result2.to_csv("/Users/shubhamarundekatey/OFLCDashboard/Mar06_merged_Whole.csv", index=False)

In [68]:
dfx = result2

In [71]:
list(dfx.columns)

['Area',
 'SocCode',
 'GeoLvl',
 'Level1',
 'Level2',
 'Level3',
 'Level4',
 'Average',
 'Label',
 'ALC_combined',
 'AreaName',
 'StateAb',
 'State',
 'CountyTownName',
 'Geo_combined',
 'OES_SOCCODE',
 'OES_SOCTITLE',
 'TruncOnetCode',
 'OnetCode',
 'ONetTitle',
 'Pro_combined']

In [74]:
dfx = dfx.drop(columns=['ALC_combined', 'Pro_combined', 'Geo_combined', 'Label'])
dfx.head()

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,AreaName,StateAb,State,CountyTownName,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
0,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,"Abilene, TX",TX,Texas,Callahan County,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
1,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,"Abilene, TX",TX,Texas,Callahan County,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
2,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,"Abilene, TX",TX,Texas,Jones County,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
3,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,"Abilene, TX",TX,Texas,Jones County,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
4,10180,11-1011,1,47.73,74.99,102.25,129.51,102.53,"Abilene, TX",TX,Texas,Taylor County,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers

In [76]:
import pandas as pd
import os

df = dfx

output_dir = "/Users/shubhamarundekatey/OFLCDashboard/DividedCSV"
os.makedirs(output_dir, exist_ok=True)

for category, group in df.groupby('OES_SOCCODE'):
    filepath = os.path.join(output_dir, f'{category}.csv')
    
    if os.path.exists(filepath):
        # Update: append new rows, drop duplicates if needed
        existing = pd.read_csv(filepath)
        updated = pd.concat([existing, group], ignore_index=True)
        updated.to_csv(filepath, index=False)
    else:
        # Create: write fresh
        group.to_csv(filepath, index=False)

# Output: output/A.csv, output/B.csv, output/C.csv

In [3]:
import pandas as pd
Pro_df = pd.read_csv("/Users/shubhamarundekatey/OFLCDashboard/OFLC_Wages_2025-26_Updated/xwalk_plus_new.csv")
Pro_df

,SOCCODE,SOCTITLE,TruncOnetCode,OnetCode,Occupation
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers
3,11-1031,Legislators,11-1031,11-1031.00,Legislators
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers
...,...,...,...,...,...
992,53-7072,"Pump Operators, Except Wellhead Pumpers",53-7072,53-7072.00,"Pump Operators, Except Wellhead Pumpers"
993,53-7073,Wellhead Pumpers,53-7073,53-7073.00,Wellhead Pumpers
994,53-7081,Refuse and Recyclable Material Collectors,53-7081,53-7081.00,Refuse and Recyclable Material Collectors
995,53-7121,"Tank Car, Truck, and Ship Loaders",53-7121,53-7121.00,"Tank Car, Truck, and Ship Loaders"
996,53-7199,"Material Moving Workers, All Other",53-7199,53-7199.00,"Material Moving Workers, All Other"

In [4]:
Pro_df['filename'] = Pro_df['SOCCODE']+'.csv'
Pro_df

,SOCCODE,SOCTITLE,TruncOnetCode,OnetCode,Occupation,filename
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers,11-1011.csv
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives,11-1011.csv
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers,11-1021.csv
3,11-1031,Legislators,11-1031,11-1031.00,Legislators,11-1031.csv
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011.csv
...,...,...,...,...,...,...
992,53-7072,"Pump Operators, Except Wellhead Pumpers",53-7072,53-7072.00,"Pump Operators, Except Wellhead Pumpers",53-7072.csv
993,53-7073,Wellhead Pumpers,53-7073,53-7073.00,Wellhead Pumpers,53-7073.csv
994,53-7081,Refuse and Recyclable Material Collectors,53-7081,53-7081.00,Refuse and Recyclable Material Collectors,53-7081.csv
995,53-7121,"Tank Car, Truck, and Ship Loaders",53-7121,53-7121.00,"Tank Car, Truck, and Ship Loaders",53-7121.csv
996,53-7199,"Material Moving Workers, All Other",53-7199,53-7199.00,"Material Moving Workers, All Other",53-7199.csv

In [5]:
Pro_df.to_csv("/Users/shubhamarundekatey/OFLCDashboard/Prof_wO_links.csv", index=False)

In [6]:
Pro_df['url'] = 'https://media.githubusercontent.com/media/deka1105/OFLCDashboard/refs/heads/main/DividedCSV/' + Pro_df['filename']
Pro_df

,SOCCODE,SOCTITLE,TruncOnetCode,OnetCode,Occupation,filename,url
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers,11-1011.csv,https://media.githubusercontent.com/media/deka...
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives,11-1011.csv,https://media.githubusercontent.com/media/deka...
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers,11-1021.csv,https://media.githubusercontent.com/media/deka...
3,11-1031,Legislators,11-1031,11-1031.00,Legislators,11-1031.csv,https://media.githubusercontent.com/media/deka...
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011.csv,https://media.githubusercontent.com/media/deka...
...,...,...,...,...,...,...,...
992,53-7072,"Pump Operators, Except Wellhead Pumpers",53-7072,53-7072.00,"Pump Operators, Except Wellhead Pumpers",53-7072.csv,https://media.githubusercontent.com/media/deka...
993,53-7073,Wellhead Pumpers,53-7073,53-7073.00,Wellhead Pumpers,53-7073.csv,https://media.githubusercontent.com/media/deka...
994,53-7081,Refuse and Recyclable Material Collectors,53-7081,53-7081.00,Refuse and Recyclable Material Collectors,53-7081.csv,https://media.githubusercontent.com/media/deka...
995,53-7121,"Tank Car, Truck, and Ship Loaders",53-7121,53-7121.00,"Tank Car, Truck, and Ship Loaders",53-7121.csv,https://media.githubusercontent.com/media/deka...
996,53-7199,"Material Moving Workers, All Other",53-7199,53-7199.00,"Material Moving Workers, All Other",53-7199.csv,https://media.githubusercontent.com/media/deka...

In [7]:
Pro_df.to_csv("/Users/shubhamarundekatey/OFLCDashboard/Prof_w_links.csv", index=False)

In [8]:
Pro_df

,SOCCODE,SOCTITLE,TruncOnetCode,OnetCode,Occupation,filename,url
0,11-1011,Chief Executives,11-1011,11-1011.03,Chief Sustainability Officers,11-1011.csv,https://media.githubusercontent.com/media/deka...
1,11-1011,Chief Executives,11-1011,11-1011.00,Chief Executives,11-1011.csv,https://media.githubusercontent.com/media/deka...
2,11-1021,General and Operations Managers,11-1021,11-1021.00,General and Operations Managers,11-1021.csv,https://media.githubusercontent.com/media/deka...
3,11-1031,Legislators,11-1031,11-1031.00,Legislators,11-1031.csv,https://media.githubusercontent.com/media/deka...
4,11-2011,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011.csv,https://media.githubusercontent.com/media/deka...
...,...,...,...,...,...,...,...
992,53-7072,"Pump Operators, Except Wellhead Pumpers",53-7072,53-7072.00,"Pump Operators, Except Wellhead Pumpers",53-7072.csv,https://media.githubusercontent.com/media/deka...
993,53-7073,Wellhead Pumpers,53-7073,53-7073.00,Wellhead Pumpers,53-7073.csv,https://media.githubusercontent.com/media/deka...
994,53-7081,Refuse and Recyclable Material Collectors,53-7081,53-7081.00,Refuse and Recyclable Material Collectors,53-7081.csv,https://media.githubusercontent.com/media/deka...
995,53-7121,"Tank Car, Truck, and Ship Loaders",53-7121,53-7121.00,"Tank Car, Truck, and Ship Loaders",53-7121.csv,https://media.githubusercontent.com/media/deka...
996,53-7199,"Material Moving Workers, All Other",53-7199,53-7199.00,"Material Moving Workers, All Other",53-7199.csv,https://media.githubusercontent.com/media/deka...

In [9]:
Pro_df[Pro_df['Occupation'].str.contains('Information Technology')]

,SOCCODE,SOCTITLE,TruncOnetCode,OnetCode,Occupation,filename,url
133,15-1299,"Computer Occupations, All Other",15-1299,15-1299.09,Information Technology Project Managers,15-1299.csv,https://media.githubusercontent.com/media/deka...